[project]
name = "pyray-2d-templates"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "nuitka>=2.7.16",
    "raylib>=5.5.0.3",
    "setuptools>=80.9.0",
]
